export const Hobbies = [
  {"id": 1, "hobby": "Cooking"},
  {"id": 2, "hobby": "Painting"},
  {"id": 3, "hobby": "Hiking"},
  {"id": 4, "hobby": "Playing musical instruments"},
  {"id": 5, "hobby": "Yoga"},
  {"id": 6, "hobby": "Writing stories"},
  {"id": 7, "hobby": "Gardening"},
  {"id": 8, "hobby": "Watching movies"},
  {"id": 9, "hobby": "Rock climbing"},
  {"id": 10, "hobby": "Learning new languages"},
  {"id": 11, "hobby": "Baking"},
  {"id": 12, "hobby": "Swimming"},
  {"id": 13, "hobby": "Reading novels"},
  {"id": 14, "hobby": "Camping"},
  {"id": 15, "hobby": "Dancing"},
  {"id": 16, "hobby": "Coding"},
  {"id": 17, "hobby": "Exploring cafes"},
  {"id": 18, "hobby": "Traveling"},
  {"id": 19, "hobby": "Playing video games"},
  {"id": 20, "hobby": "Volunteering"},
  {"id": 21, "hobby": "Photography"},
  {"id": 22, "hobby": "martial arts"},
  {"id": 23, "hobby": "Attending concerts"},
  {"id": 24, "hobby": "DIY crafts"}
    ];